socialnet/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "post/<int:post_id>/<slug:post_slug>/",
        views.DetailViewPost.as_view(),
        name="post_detail",
    ),
    path(
        "post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name="post_delete"
    ),
    path(
        "post/update/<int:post_id>/", views.PostUpdateView.as_view(), name="post_update"
    ),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "reply/<int:post_id>/<int:comment_id>",
        views.PostAddReplyView.as_view(),
        name="post_create",
    ),
    path(
        "like/<int:post_id>/",
        views.PostLikeView.as_view(),
        name="post_like",
    ),
]

socialnet/socialnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
]

socialnet/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateField(auto_now_add=True)
    update = models.DateField(auto_now=True)

    class Meta:
        ordering = ("created", "body")

    def __str__(self) -> str:
        return f"{self.slug} -> {self.user} - {self.created}"

    def get_absolute_url(self):
        return reverse("home:post_detail", args=[self.pk, self.slug])

    def likes_count(self):
        return self.pvotes.count()

    def user_can_like(self, user):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ucomments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pcomments")
    is_reply = models.BooleanField(default=False)
    reply = models.ForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True, related_name="rcomments"
    )
    body = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.user} - {self.body[:30]}"


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uvotes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pvotes")

    def __str__(self) -> str:
        return f"{self.user} liked {self.post.slug}"

socialnet/home/forms.py
from django import forms
from .models import Post, Comment


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("body",)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {"body": forms.Textarea(attrs={"class": "form-control"})}


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {"body": forms.Textarea(attrs={"class": "form-control"})}


class PostSearch(forms.Form):
    search = forms.CharField()

socialnet/home/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.views import View
from .models import Post, Comment, Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostUpdateForm, CommentForm, CommentReplyForm, PostSearch
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.


class HomeView(View):
    form_class = PostSearch

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get("search"):
            posts = posts.filter(body__contains=request.GET["search"])

        return render(
            request, "home/index.html", {"posts": posts, "form": self.form_class}
        )


class DetailViewPost(View):
    form_class = CommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instance = get_object_or_404(
            Post, pk=kwargs["post_id"], slug=kwargs["post_slug"]
        )
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args: Any, **kwargs: Any):
        # post1 = get_object_or_404(
        #     Post,
        #     id=post_id,
        #     slug=post_slug,
        # )
        # post2 = Post.objects.get(
        #     id=post_id,
        #     slug=post_slug,
        # )
        comment = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(
            request.user
        ):
            can_like = True
        return render(
            request,
            "home/detail.html",
            {
                "post": self.post_instance,
                "comments": comment,
                "form": self.form_class,
                "reply_form": self.form_class_reply,
                "can_like": can_like,
            },
        )

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post
            new_comment.save()
            messages.success(request, "comment added", "success")
            return redirect(
                "home:post_detail", self.post_instance.pk, self.post_instance.slug
            )


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        # post = Post.objects.get(pk=post_id)
        if post.user.pk == request.user.id:
            post.delete()
            messages.success(request, "post deleted successfuly", "success")
        else:
            messages.error(request, "you can not delete the post", "danger")
        return redirect("home:home")


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostUpdateForm

    def setup(self, request: HttpRequest, *args: Any, **kwargs: Any) -> None:
        self.post_instanse = Post.objects.get(pk=kwargs["post_id"])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any):
        post = self.post_instanse
        if not post.user.pk == request.user.pk:
            messages.error(request, "you can not update post", "danger")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instanse
        form = self.form_class(instance=post)
        return render(request, "home/update.html", {"form": form})

    def post(self, request, *args, **kwargs):
        post = self.post_instanse
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.save()
            messages.success(request, "post changed successfuly", "success")
            return redirect("home:post_detail", post.pk, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostUpdateForm

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, "home/create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data["body"][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, "post create successfuly", "success")
            return redirect("home:post_detail", new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, "your reply submit successful ", "success")
        return redirect("home:post_detail", post.pk, post.slug)


class PostLikeView(LoginRequiredMixin, View):

    def get(self, request, post_id):
        post = get_object_or_404(Post, post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, "you liked this post already", "warning")
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, "like", "success")
        return redirect("home:post_detail", post.pk, post.slug)

socialnet/home/templates/home/create.html
{% extends 'base.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

{% endblock %}

socialnet/home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}

{% if request.user.id == post.user.id %}

<a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
<a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>


{% endif %}

<p class="card">
    {{ post.user }}
    -> updatedin :
    {{ post.update | date:"Y M" }}
    -> createdin :
    {{ post.created | date:"Y M"}}
</p>

<p>
    {{ post.body }}
</p>
<hr>

<p>{{ comments.count }} comments </p>

{% if request.user.is_authenticated %}

<a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %}  btn btn-primary col-md-1">like {{ post.likes_count }}</a>

<form action="" method="post">
    {% csrf_token %}
    {{ form.is_p }}
        <input type="submit" value="send">
</form>
<br>
{% else %}
<p class="alert alert-danger">only loged in user can comment</p>
{% endif %}

{% for comment in comments %}
<div class="card bg-dark text-white">
         <p class="card-header">{{ comment.user }} || {{ comment.created|timesince }}</p>
    <p class="card-body">{{ comment.body }}</p>

    {% if request.user.is_authenticate %}
    <form action="{% url 'home:add_repky' post.id comment.id %}" class="post">
        {% csrf_token %}
        {{ reply_form.is_p }}

        <input type="submit" value="send">
    </form>
    {% endif %}

    {% with replies=comment.rcomments.all %}
    {% for reply in replies %}
    <p class="bg-primary p-3 m-2">{{ reply.user }} <br> {{reply.body}}</p>
    {% endfor %}
    {% endwith %}

</div>
<br>

{% empty %}

<p>no comment yet</p>
{% endfor %}

{% endblock %}

socialnet/home/templates/home/index.html
{% extends 'base.html' %}



{% block content %}
        <form action="" method="get">
            {{ form.as_p }}
            <input type="submit" value="search">
        </form><br><br/>
index page :
<div class="card">
    {% for post in posts %}
    <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body | truncatewords:8 }}</a>
    {% endfor %}
</div>

{% endblock %}

socialnet/home/templates/home/update.html
{% extends 'base.html' %}

{% block content %}



<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}