socialnet/account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("register/", views.RegisterUser.as_view(), name="register_user"),
    path("login/", views.LoginUserForm.as_view(), name="login_user"),
    path("logout/", views.UserLogoutForm.as_view(), name="logout_user"),
    path(
        "profile/<int:user_id>/", views.UserProfileView.as_view(), name="profile_user"
    ),
    path("reset/", views.UserPasswordResetView.as_view(), name="password_reset"),
    path(
        "reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "confirm/complete/",
        views.UserPasswordResetCompeleteView.as_view(),
        name="password_reset_compelete",
    ),
    path('follow/<int:user_id>',views.UserFollowView.as_view(),name='user_follow'),
    path('unfollow/<int:user_id>',views.UserUnFollowView.as_view(),name='user_unfollow'),
    path('edit_user/',views.UserEditView.as_view(),name='edit_user')


]

socialnet/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "post/<int:post_id>/<slug:post_slug>/",
        views.DetailViewPost.as_view(),
        name="post_detail",
    ),
    path(
        "post/delete/<int:post_id>/", views.PostDeleteView.as_view(), name="post_delete"
    ),
    path(
        "post/update/<int:post_id>/", views.PostUpdateView.as_view(), name="post_update"
    ),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "reply/<int:post_id>/<int:comment_id>",
        views.PostAddReplyView.as_view(),
        name="post_create",
    ),
    path(
        "like/<int:post_id>/",
        views.PostLikeView.as_view(),
        name="post_like",
    ),
]

socialnet/socialnet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
]

socialnet/templates/inc/messages.html
{% if messages %}

{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
{% endfor %}

{% endif %}

socialnet/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'home:home' %}">HOME</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'account:logout_user' %}">LOGOUT</a>
            <a class="nav-link active" href="{% url 'account:profile_user' request.user.id %}">PROFILE</a>

            {% else %}
            <a class="nav-link active" href="{% url 'account:register_user' %}">REGISTER</a>
            <a class="nav-link active" href="{% url 'account:login_user' %}">LOGIN</a>
            {% endif %}
        </div>
    </div>

</nav>